### PR TITLE
Update for 0.3.3

### PR DESCRIPTION
**Pull request by mountainMath**
Getting ready for v0.3.3

Fix warning from new version of tibble and dplyr.
Added get_intersection_geometries
experimental install_api_key function

### CODE REVIEW

**Comment by dshkol** [comment]
Added some minor changes and tweaks to the intersect geo branch. Still need to add the vignette for it too.

**Comment by mountainMath** [comment]
I will do some work on the sever to facilitate opening this up to a general audience. Not sure how to best do this, will have to better understand impacts on server first. Might introduce a new api quota counter for this.

**Comment by dshkol** [comment]
> I will do some work on the sever to facilitate opening this up to a general audience. Not sure how to best do this, will have to better understand impacts on server first. Might introduce a new api quota counter for this.

Do you want to run diagnostics first using this branch and then decide? If the cost is high, I'm fine with not pushing this feature publicly.

**Comment by dshkol** [comment]
Let me know if you decide to go ahead with this and I'll start on the vignette. I will document when to use this feature and when to just download geo and do spatial operations locally.

**Review by dshkol — COMMENTED** [review]
Does the cost of the API operation depend on the area or the number of intersections? By taking the area of the geo, is there not a risk that large sparse areas may be flagged here despite having few intersections?

**Comment by mountainMath** [comment]
If I take a bounding box for Canada and query just the number (count) of DAs it takes 15 seconds on my local machine. That goes up if I make the boundary more complex or e.g. query DBs. So it's hard to estimate the 'cost' without actually incurring it. So I was thinking of using area and string length of the geojson as a proxy. There probably are better ways, will have to think about it more.

**Comment by dshkol** [comment]
> If I take a bounding box for Canada and query just the number (count) of DAs it takes 15 seconds on my local machine. That goes up if I make the boundary more complex or e.g. query DBs. So it's hard to estimate the 'cost' without actually incurring it. So I was thinking of using area and string length of the geojson as a proxy. There probably are better ways, will have to think about it more.

Thinking about this a bit more, the average compactness of urban DAs is likely lower and more rectangular-ish than the unusual shapes of rural and northern geographies, so using area and string length might disproportionately affect those queries, even if the total number of cells pulled is much smaller. For example the disk size of the geo object for all CSDs is almost 5x the size of the one for all CTs despite being slightly lower in count. 

I was thinking perhaps we can use latitude as a proxy for complexity of the query? Here's the centroids of CTs by latitude:

image

And here's CSDs

image

Maybe we can have some kind of function that does a super quick guess of expected complexity of the query by taking the bounding box of the spatial object and inferring based on its approximate location how complex that query is likely to be.

**Comment by mountainMath** [comment]
Ok, I think I have a plan. I'll first run the estimate at the CSD level no matter what. That's a lot fewer geographies and runs pretty fast, especially if I use simplified CD geometries. Then I can
a) get an idea of the spatial extent and
b) save on the consecutive spatial query by filtering by the CDs from step 1. (Although that probably means I will have add another index.)

That way I can limit at least some requests that take a lot of resources. Maybe I will categorically restrict free access to requests within a single CD. Or maybe if it's CT level I will allow several CDs, if DA than only 1.

**Comment by mountainMath** [comment]
Strange. Works fine for me. Here is my session info.

```
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.3.2   cancensus_0.3.3 sf_0.9-6        dplyr_1.0.2    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5         pillar_1.4.7       compiler_4.0.3     class_7.3-17       tools_4.0.3       
 [6] digest_0.6.27      downlit_0.2.0      gtable_0.3.0       jsonlite_1.7.2     evaluate_0.14     
[11] memoise_1.1.0      lifecycle_0.2.0    tibble_3.0.4       pkgconfig_2.0.3    rlang_0.4.9       
[16] cli_2.2.0          DBI_1.1.0          rstudioapi_0.13    curl_4.3           yaml_2.2.1        
[21] pkgdown_1.6.1      xfun_0.18          e1071_1.7-4        withr_2.3.0        httr_1.4.2        
[26] knitr_1.30         desc_1.2.0         generics_0.1.0     fs_1.4.1           vctrs_0.3.5       
[31] hms_0.5.3          grid_4.0.3         classInt_0.4-3     triebeard_0.3.0    rprojroot_2.0.2   
[36] tidyselect_1.1.0   glue_1.4.2         geojsonsf_2.0.0    R6_2.5.0           processx_3.4.5    
[41] fansi_0.4.1        rmarkdown_2.5      purrr_0.3.4        callr_3.5.1        VancouvR_0.1.1    
[46] readr_1.4.0        magrittr_2.0.1     rematch2_2.1.2     scales_1.1.1       usethis_1.6.1     
[51] units_0.6-7        urltools_1.7.3     ps_1.5.0           ellipsis_0.3.1     htmltools_0.5.0   
[56] assertthat_0.2.1   colorspace_2.0-0   KernSmooth_2.23-17 munsell_0.5.0      lwgeom_0.2-5      
[61] crayon_1.3.4      
```

**Comment by dshkol** [comment]
> Strange. Works fine for me. Here is my session info.
> 
> ```
> > sessionInfo()
> R version 4.0.3 (2020-10-10)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Big Sur 10.16
> 
> Matrix products: default
> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] ggplot2_3.3.2   cancensus_0.3.3 sf_0.9-6        dplyr_1.0.2    
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.5         pillar_1.4.7       compiler_4.0.3     class_7.3-17       tools_4.0.3       
>  [6] digest_0.6.27      downlit_0.2.0      gtable_0.3.0       jsonlite_1.7.2     evaluate_0.14     
> [11] memoise_1.1.0      lifecycle_0.2.0    tibble_3.0.4       pkgconfig_2.0.3    rlang_0.4.9       
> [16] cli_2.2.0          DBI_1.1.0          rstudioapi_0.13    curl_4.3           yaml_2.2.1        
> [21] pkgdown_1.6.1      xfun_0.18          e1071_1.7-4        withr_2.3.0        httr_1.4.2        
> [26] knitr_1.30         desc_1.2.0         generics_0.1.0     fs_1.4.1           vctrs_0.3.5       
> [31] hms_0.5.3          grid_4.0.3         classInt_0.4-3     triebeard_0.3.0    rprojroot_2.0.2   
> [36] tidyselect_1.1.0   glue_1.4.2         geojsonsf_2.0.0    R6_2.5.0           processx_3.4.5    
> [41] fansi_0.4.1        rmarkdown_2.5      purrr_0.3.4        callr_3.5.1        VancouvR_0.1.1    
> [46] readr_1.4.0        magrittr_2.0.1     rematch2_2.1.2     scales_1.1.1       usethis_1.6.1     
> [51] units_0.6-7        urltools_1.7.3     ps_1.5.0           ellipsis_0.3.1     htmltools_0.5.0   
> [56] assertthat_0.2.1   colorspace_2.0-0   KernSmooth_2.23-17 munsell_0.5.0      lwgeom_0.2-5      
> [61] crayon_1.3.4      
> ```

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_0.9-5        ggplot2_3.3.2   dplyr_1.0.2     cancensus_0.3.3

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5         pillar_1.4.6       compiler_4.0.2     class_7.3-17      
 [5] tools_4.0.2        digest_0.6.25      jsonlite_1.7.1     lifecycle_0.2.0   
 [9] tibble_3.0.3       gtable_0.3.0       pkgconfig_2.0.3    rlang_0.4.9       
[13] cli_2.0.2          DBI_1.1.0          rstudioapi_0.11    curl_4.3          
[17] xfun_0.19          e1071_1.7-3        httr_1.4.2         withr_2.2.0       
[21] knitr_1.29         generics_0.0.2     vctrs_0.3.6        classInt_0.4-3    
[25] grid_4.0.2         tidyselect_1.1.0   glue_1.4.2         geojsonsf_2.0.0   
[29] R6_2.4.1           fansi_0.4.1        sessioninfo_1.1.1  purrr_0.3.4       
[33] magrittr_1.5       scales_1.1.1       ellipsis_0.3.1     htmltools_0.5.0   
[37] units_0.6-7        assertthat_0.2.1   colorspace_1.4-1   KernSmooth_2.23-17
[41] utf8_1.1.4         munsell_0.5.0      lwgeom_0.2-5       crayon_1.3.4  
```

**Comment by dshkol** [comment]
> > Strange. Works fine for me. Here is my session info.
> > ```
> > > sessionInfo()
> > R version 4.0.3 (2020-10-10)
> > Platform: x86_64-apple-darwin17.0 (64-bit)
> > Running under: macOS Big Sur 10.16
> > 
> > Matrix products: default
> > LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
> > 
> > locale:
> > [1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8
> > 
> > attached base packages:
> > [1] stats     graphics  grDevices utils     datasets  methods   base     
> > 
> > other attached packages:
> > [1] ggplot2_3.3.2   cancensus_0.3.3 sf_0.9-6        dplyr_1.0.2    
> > 
> > loaded via a namespace (and not attached):
> >  [1] Rcpp_1.0.5         pillar_1.4.7       compiler_4.0.3     class_7.3-17       tools_4.0.3       
> >  [6] digest_0.6.27      downlit_0.2.0      gtable_0.3.0       jsonlite_1.7.2     evaluate_0.14     
> > [11] memoise_1.1.0      lifecycle_0.2.0    tibble_3.0.4       pkgconfig_2.0.3    rlang_0.4.9       
> > [16] cli_2.2.0          DBI_1.1.0          rstudioapi_0.13    curl_4.3           yaml_2.2.1        
> > [21] pkgdown_1.6.1      xfun_0.18          e1071_1.7-4        withr_2.3.0        httr_1.4.2        
> > [26] knitr_1.30         desc_1.2.0         generics_0.1.0     fs_1.4.1           vctrs_0.3.5       
> > [31] hms_0.5.3          grid_4.0.3         classInt_0.4-3     triebeard_0.3.0    rprojroot_2.0.2   
> > [36] tidyselect_1.1.0   glue_1.4.2         geojsonsf_2.0.0    R6_2.5.0           processx_3.4.5    
> > [41] fansi_0.4.1        rmarkdown_2.5      purrr_0.3.4        callr_3.5.1        VancouvR_0.1.1    
> > [46] readr_1.4.0        magrittr_2.0.1     rematch2_2.1.2     scales_1.1.1       usethis_1.6.1     
> > [51] units_0.6-7        urltools_1.7.3     ps_1.5.0           ellipsis_0.3.1     htmltools_0.5.0   
> > [56] assertthat_0.2.1   colorspace_2.0-0   KernSmooth_2.23-17 munsell_0.5.0      lwgeom_0.2-5      
> > [61] crayon_1.3.4      
> > ```
> 
> ```
> > sessionInfo()
> R version 4.0.2 (2020-06-22)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Mojave 10.14.6
> 
> Matrix products: default
> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] sf_0.9-5        ggplot2_3.3.2   dplyr_1.0.2     cancensus_0.3.3
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.5         pillar_1.4.6       compiler_4.0.2     class_7.3-17      
>  [5] tools_4.0.2        digest_0.6.25      jsonlite_1.7.1     lifecycle_0.2.0   
>  [9] tibble_3.0.3       gtable_0.3.0       pkgconfig_2.0.3    rlang_0.4.9       
> [13] cli_2.0.2          DBI_1.1.0          rstudioapi_0.11    curl_4.3          
> [17] xfun_0.19          e1071_1.7-3        httr_1.4.2         withr_2.2.0       
> [21] knitr_1.29         generics_0.0.2     vctrs_0.3.6        classInt_0.4-3    
> [25] grid_4.0.2         tidyselect_1.1.0   glue_1.4.2         geojsonsf_2.0.0   
> [29] R6_2.4.1           fansi_0.4.1        sessioninfo_1.1.1  purrr_0.3.4       
> [33] magrittr_1.5       scales_1.1.1       ellipsis_0.3.1     htmltools_0.5.0   
> [37] units_0.6-7        assertthat_0.2.1   colorspace_1.4-1   KernSmooth_2.23-17
> [41] utf8_1.1.4         munsell_0.5.0      lwgeom_0.2-5       crayon_1.3.4  
> ```

Might have something to do with this: https://github.com/r-spatial/sf/issues/1450. Only place I'm seeing the exact error code. What version `sf` are you using? I don't see it in your sessionInfo. Could be that I'm on a slightly outdated version that doesnt capture this bug. If that is the case let's see if we can work around it for some backwards compatibility.

**Comment by mountainMath** [comment]
Says sf_0.9-6 in mine, so maybe that's the issue?

**Comment by dshkol** [comment]
> Says sf_0.9-6 in mine, so maybe that's the issue?

Yep, fixed it. I think we should flag that and see if we can work around this. `sf-0.9.5` isn't even that old. If hard to fix then we can roll up the min dependency for it.

**Comment by dshkol** [comment]
Seems to still fail with old R on Ubuntu, this time because it can't install the `leaflet` package. 
```
there is no package called 'leaflet'
```

**Comment by mountainMath** [comment]
Hmm. Will try to explicitly install leaflet in the GitHub action.

**Comment by mountainMath** [comment]
Ok, explicit installing leaflet fails too. The issue is that leaflet depends on raster. And raster requires R version 3.4-5. https://cran.r-project.org/web/packages/raster/index.html.

**Pull request merged**
