### PR TITLE
fix issue with reading in large geojson files failing

### PR DESCRIPTION
**Pull request by mountainMath**
Fixes https://github.com/mountainMath/cancensus/issues/138

### CODE REVIEW

**Comment by mountainMath** [comment]
This should also fix https://github.com/mountainMath/cancensus/issues/137

**Comment by dshkol** [comment]
Travis error
> Error: package ‘Rcpp’ was installed before R 4.0.0: please re-install it
Looks like we might as well check how things work on R 4.0.0 with this release

**Comment by dshkol** [comment]
That last fail is on the vignette. It’s due to an error in the latest version of ‘sfheaders’ as used by mapdeck. Flagged the issue with the package author and he’s looking to release a CRAN fix. Do can either revert the commit and drop the vignette change or wait it out.

**Comment by mountainMath** [comment]
Hmm. Is there a branch that we can install manually on travis to make this run through? It's precompiled for CAN anyway, and the package updates will probably land at about the same time.

Also, I added an environment variable for mapbox tiles to travis just in case.

**Comment by dshkol** [comment]
> Hmm. Is there a branch that we can install manually on travis to make this run through? It's precompiled for CAN anyway, and the package updates will probably land at about the same time.
> 
> Also, I added an environment variable for mapbox tiles to travis just in case.

The dev version of `sfheaders` works fine, but I think I will just stash the extension of the vignette and just focus on releasing this one as is without any further delay (entirely from my end, waiting until now to do all of this).

**Pull request merged**
