### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by dshkol**
This PR updates the readme page, adds a news page, and updates the description file to increment the version up to 0.1.5 and improve dependencies for vignettes.

### CODE REVIEW

**Comment by atheriel** [comment]
Again, it looks like this has stray commits. You can rebase this branch to remove them, or I can do that if you'd like.

**Comment by atheriel** [comment]
Also at some point we should tag the commits where the version changes so that GitHub will understand them as releases correctly.

**Comment by dshkol** [comment]
Go ahead if you want. I need to sharpen up on command line git in the future.

**Comment by dshkol** [comment]
Is there a good practices guideline for R package versioning?

**Comment by atheriel** [comment]
I think people try to adhere to semantic versioning for the most part (i.e. if the API gets more features, increment the minor version, if it's just bug fixes or something increment the patch version). For pre-release versions though I doubt anyone is all that careful. When this makes it to CRAN we should change the version to `0.2.0` and label it "First public beta", and then just label pre-`0.2.0` versions as "alpha" releases. After that we'd change the version number whenever we make incompatible API changes, or add new features.

**Comment by atheriel** [comment]
@dshkol Are you currently working on this branch? If not, can I rebase it to clean up the duplicate commits?

**Comment by dshkol** [comment]
I won't have a chance to make anything besides web-edits until tonight, so don't worry about me.

**Comment by atheriel** [comment]
Ok, I've cleaned up the history. The content looks fine to me, so I'll just merge it.

**Pull request merged**
