### PR TITLE
Various R CMD check fixes

### PR DESCRIPTION
**Pull request by atheriel**
In preparation for uploading to CRAN, this PR makes several small fixes to the package to silence warnings, errors, or notes in `R CMD check`. The only real change of note is that we will have to use the `.data` object from **rlang** to silence all of the "missing binding for global variable" errors in **dplyr** code. I know this is ugly as hell, but it's currently the recommended best practice until `R CMD check` gets better at detecting **dplyr** code.

It's my goal to have Travis "pass" this PR before merging.

### CODE REVIEW

**Comment by atheriel** [comment]
@mountainMath Travis is saying that there is no API key. Did it get removed somehow?

**Comment by mountainMath** [comment]
Hmm. Just checked, the CM_API_KEY environment variable is still set on travis.

**Comment by mountainMath** [comment]
I have a couple of meetings this morning, will check in again later today. Could it be that R CMD does not properly grab the environment variables, maybe needs them passed in by hand?

**Comment by mountainMath** [comment]
Not sure what's going on. If I run `R CMD build .` locally it reads the environment variable correctly, but gets hung up after that with a `cannot open the connection` message.

**Comment by mountainMath** [comment]
I think the problem might be that the pull request comes in as a fork, not from a different branch on the same repo. If I read this correctly, Travis won't make the environment variable available in that case. https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

**Comment by mountainMath** [comment]
I have created a "development" branch, will need one sooner or later anyway. Maybe merging this fork into development branch first will circumvent the travis problem. Want to make a pull request into the development branch @atheriel ?

**Comment by dshkol** [comment]
Could you could clone @atheriel's fork with my conflict resolves and merge that into dev?

**Comment by atheriel** [comment]
I'm happy to rebase this, which should resolve the conflicts -- but I wanted it to sit until it actually passed the checks, hence waiting a little. It looks like @mountainMath figured it out, though: I was not aware of the fork/branch distinction.

The build is now passing on that branch (visible in #105), although it looks like [I have one more](https://travis-ci.org/mountainMath/cancensus#L2529) `R CMD check` issue to fix! If there's no objection I'll open another PR. The alternative is to add another commit to this one, revert the merge, and then merge it again. Thoughts?

**Comment by mountainMath** [comment]
Either way works for me.

**Comment by atheriel** [comment]
Obviated by #106.

**Pull request merged**
