### PR TITLE
Tidy up

### PR DESCRIPTION
**Pull request by dshkol**
Make less verbose where appropriate:

* Trying to use while and for loops as little as possible in a vignette
* Simplify code where feasible
* Use gather rather than reshape
* ggplot can do a lot towards stacked bar graphs on its own without needing data prep
* Automate colour selection

### CODE REVIEW

**Comment by mountainMath** [comment]
Good in general, but I think we should keep the code that grabs all dependent vectors flexible. The current version only works in cases where the hierarchy is only 2 levels deep.

Actually, I think we should put that code into two convenience functions as suggested in https://github.com/mountainMath/cancensus/issues/52. This will come handy in other cases too.

**Comment by dshkol** [comment]
Yes I agree. In this case it works because it's only 2 levels deep, but in the near future we can replace it with the convenience function to do just that.

**Comment by mountainMath** [comment]
ok. let's pull this into master for now.

**Comment by dshkol** [comment]
#57 is the correct one. I was trying to push from command line directly and making changes online. Note to self - don't mix the two.

**Pull request closed without merging**
